name: Scheduled Tests

on:
  schedule:
    - cron: '00 20 * * *'
    
  workflow_dispatch:

jobs:
  build:
    name: Build Java application
    runs-on: ubuntu-20.04
    
    steps:
    
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build native with Maven
      run: mvn -B package -DskipTests
      
    - name: Test unitario
      run: mvn -B '-Dtest=es.urjc.code.daw.library.unitary.*Test' test
      
    - name: Test REST
      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.rest.*Test' test
      
    - name: Test Selenium
      run: mvn -B '-Dtest=es.urjc.code.daw.library.e2e.selenium.*Test' test
      
    - name: Upload jar for next job
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
        retention-days: 1
        
  publish_in_dockerhub:
  
    name: Publish in DockerHub
    runs-on: ubuntu-20.04
    needs: [build]
    
    steps:
    
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target
          
      - name: Generate tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d.%H%M%S')
        id: project
        
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}" 
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/items:dev-${{ steps.project.outputs.tag }} .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/items:dev-${{ steps.project.outputs.tag }}
